FROM osrf/ros:humble-desktop

# -------------------------------------------------------------
# 1. Install System + ROS + MoveIt Dependencies
# -------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    python3-pip python3-venv python3-dev \
    build-essential cmake git wget unzip \
    libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module \
    libv4l-dev v4l-utils \
    \
    # ROS2 MoveIt packages
    ros-humble-moveit \
    ros-humble-moveit-common \
    ros-humble-moveit-msgs \
    ros-humble-moveit-ros-planning \
    ros-humble-moveit-ros-move-group \
    ros-humble-moveit-servo \
    \
    # ROS2 control & controllers
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-controller-manager \
    \
    # ROS message packages required for MoveIt Python API
    ros-humble-geometry-msgs \
    ros-humble-sensor-msgs \
    ros-humble-trajectory-msgs \
    \
    # Joint state publishers
    ros-humble-joint-state-publisher \
    ros-humble-joint-state-publisher-gui \
    ros-humble-robot-state-publisher \
    \
    # Serial communication
    python3-serial \
    \
    # ros2_kortex dependencies
    ros-humble-xacro \
    ros-humble-backward-ros \
    && rm -rf /var/lib/apt/lists/*


# -------------------------------------------------------------
# 2. Clone & Build ros2_kortex (real arm packages only, no Gazebo)
# -------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    ros-humble-xacro \
    ros-humble-backward-ros \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /kortex_ws/src

RUN git clone -b humble https://github.com/Kinovarobotics/ros2_kortex.git /kortex_ws/src/ros2_kortex && \
    cd /kortex_ws/src/ros2_kortex && \
    git checkout 3ca0e71

RUN /bin/bash -c ". /opt/ros/humble/setup.sh && \
    cd /kortex_ws && \
    rosdep install --from-paths src --ignore-src -r -y \
        --skip-keys 'picknik_reset_fault_controller picknik_twist_controller robotiq_description gazebo_ros2_control' && \
    colcon build --symlink-install"

ENV AMENT_PREFIX_PATH="/kortex_ws/install"
ENV PYTHONPATH="/kortex_ws/install/lib/python3.10/site-packages"
