FROM osrf/ros:jazzy-desktop

# -------------------------------------------------------------
# 1. Install System + ROS + MoveIt Dependencies
# -------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    python3-pip python3-venv python3-dev \
    build-essential cmake git wget unzip \
    libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module \
    libv4l-dev v4l-utils \
    \
    # ROS2 MoveIt packages
    ros-jazzy-moveit \
    ros-jazzy-moveit-common \
    ros-jazzy-moveit-msgs \
    ros-jazzy-moveit-ros-planning \
    ros-jazzy-moveit-ros-move-group \
    ros-jazzy-moveit-servo \
    \
    # ROS2 control & controllers
    ros-jazzy-ros2-control \
    ros-jazzy-ros2-controllers \
    ros-jazzy-controller-manager \
    \
    # ROS message packages required for MoveIt Python API
    ros-jazzy-geometry-msgs \
    ros-jazzy-sensor-msgs \
    ros-jazzy-trajectory-msgs \
    \
    # Joint state publishers
    ros-jazzy-joint-state-publisher \
    ros-jazzy-joint-state-publisher-gui \
    ros-jazzy-robot-state-publisher \
    \
    # Serial communication
    python3-serial \
    \
    # ros2_kortex dependencies
    ros-jazzy-xacro \
    ros-jazzy-backward-ros \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------
# 2. Clone & Build ros2_kortex (jazzy branch)
# -------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    ros-jazzy-xacro \
    ros-jazzy-backward-ros \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /kortex_ws/src

RUN git clone -b jazzy https://github.com/Kinovarobotics/ros2_kortex.git /kortex_ws/src/ros2_kortex

RUN /bin/bash -c ". /opt/ros/jazzy/setup.sh && \
    cd /kortex_ws && \
    rosdep install --from-paths src --ignore-src -r -y \
    --skip-keys 'picknik_reset_fault_controller picknik_twist_controller robotiq_description gazebo_ros2_control gz_ros2_control ros_gz_bridge ros_gz_sim' && \
    colcon build --symlink-install"

ENV AMENT_PREFIX_PATH="/kortex_ws/install"
ENV PYTHONPATH="/kortex_ws/install/lib/python3.12/site-packages"